### PR TITLE
OOP - Milestone 4: Game instructions and final touches

### PR DESCRIPTION
**Pull request by vicmaburrito**
Added a full description of game rules and flow in README file

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] N/A

- ### To Improve
  - [x] [MANDATORY] This branch `readme_game_instructions` should have everything implemented in the previous milestones, which means that you should have created it from the `development` branch after merging every milestone to it. but for now, just merge milestone3(which now has the latest working code of your game) to the `development` branch. and then follow these steps to perform rebase.
     - go to project root in your cmd and then go to `development` branch with `git checkout development` and `git pull origin development` to pull the merged changes.
     - the go back to `readme_game_instructions` with `git checkout readme_game_instructions`
     - then run `git rebase origin/development` or `git rebase development` to perfom rebase.
     - If there are any conflicts - resolve them and then run `git rebase --continue`
     - Find more [Here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) on how to rebase branches in git.
  - [x] [MANDATORY] In the readme, you instructed that game should be started by running `ruby main.rb` but according to the folder structure of this project, this will not work.
  - [x] [MANDATORY] And since this is the last touch on this project, the instructions should not contain other previous milestones. like where you instructed to switch to the game_logic branch.  

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Comment by vicmaburrito** [comment]
When I fixed the conflicts with the development branch I did more conflicts because I cannot rebase the branch

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Requires changes :yellow_circle: 
### Hello  @Gnwin and @vicmaburrito :wave: 

#### Thanks for your submission.  

### I really like your project :+1:  and it passes most of the requirements but you should work on all suggested requirements made by the previous TSE. 
- Please fix instructions to start the game. If I am new to your repo and follow your instructions and run ``` ruby main.rb```, the game will not start. Kindly fix it to 
```ruby bin/main```

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
#### Good job Team :100: :1st_place_medal:
#### This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
